## Actividades semana 2

### 1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.

In [16]:
import pandas as pd

dat_csv = pd.read_csv("ventas (1).csv", encoding="ISO-8859-1")

dat_csv.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

Profesor intente de tantas maneras posibles abrir mi csv desde la ruta de acceso, con la carpeta de la computadora pero no pude por lo que me traje el csv y lo abri asi directamente. Espero este bien ejecutado. Pude entender que one drive se adueñó de  mi escritorio y no me deja traerlo desde la ruta.

### 2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

In [23]:
import pandas as pd

clientes = pd.read_json("clientes.json")

clientes.head()

   id_cliente        nombre             email   telefono
0           1    Juan Pérez    juan@email.com  123456789
1           2   María López   maria@email.com  987654321
2           3  Carlos Gómez  carlos@email.com  456123789

In [24]:
len(clientes)

3

### 3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos

In [25]:
import pandas as pd

inventario = pd.read_excel("inventario.xlsx")

inventario.head()

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

In [26]:
inventario.columns

Index(['id_producto', 'nombre', 'categoria', 'stock', 'precio'], dtype='object')

In [27]:
print("Promedio de stock:", inventario["stock"].mean())

Promedio de stock: 26.25

### Se importaron datos desde distintos formatos (CSV, JSON y Excel), permitiendo trabajar con múltiples fuentes de información dentro de un mismo entorno utilizando la librería Pandas. Tuve bastantes problemas para poder cargar los archivos copiando la ruta de acceso.Lo solucioné trayendo los archivos para el notebook en el que estoy trabajando y los cargue desde acá. Tambien voy a agregar una carpeta con los archivos para tarea de la semana 2 en mi git para que quede mas prolijo. Muchas Gracias . Saludos